### ISSUE TITLE
plugin doesn't run

### ISSUE THREAD

**Issue by fhorlaville** [capistrano/drupal-deploy#2]
Hi, I'm having an issue where the plugin is installed, it appears in cap -T, but it does't seem to do anything

e.g.:

$ cap qa --trace drupal:logs
*\* Invoke qa (first_time)
*\* Execute qa
*\* Invoke load:defaults (first_time)
*\* Execute load:defaults
*\* Invoke drupal:logs (first_time)
*\* Execute drupal:logs

If I put a typo in the task name, such as drupal:logz I do receive an error.
If I add tasks in the :drupal namespace I can call and execute them fine.
I also tried removing the gem and copying the code into a .rake file with the same results.

We're on a multisite drupal 7 with no default settings

any pointers ? I've tried most if not all of the commands but nothing happens.

Thanks !

**Comment by quintencls** [comment]
Do you deploy with the role 'app'? All Drupal related tasks seem to be scoped to that role.

**Comment by gagarine** [comment]
Did you set: 
set :app_path,        "app"   // <- your drupal directory

**Comment by gagarine** [comment]
Can you please post your capistrano config?

**Comment by fhorlaville** [comment]
Apologies to both of you, I had not noticed that I had received answers.

@quintencls nailed it - I had not added the role 'app' to the relevant servers

Now it seems I'm having drush issues but it's another story, I need to investigate.

```
INFO [92767dff] Running /usr/bin/env drush watchdog-show  --tail as user@qa.example.com
DEBUG [92767dff] Command: cd /home/www/drup/current/web && /usr/bin/env drush watchdog-show  --tail
DEBUG [92767dff]        PHP Fatal error:  Call to undefined function module_exists() in /usr/local/src/drush/commands/core/drupal/environment_7.inc on line 187
DEBUG [92767dff]        Drush command terminated abnormally due to an unrecoverable error.       [error]
DEBUG [92767dff]        Error: Call to undefined function module_exists() in
DEBUG [92767dff]        /usr/local/src/drush/commands/core/drupal/environment_7.inc, line 187
cap aborted!
```

Thanks a lot to both of you and apologies again for the late reply
