### ISSUE TITLE
Improve documentation for reverting/rollback

### ISSUE THREAD

**Issue by jameswilson** [capistrano/drupal-deploy#5]
One of the initial things people (well, at least our team)  looked at in evaluating the feasibility of switching to capistrano off of our current ci/deployment system based on Jenkins and custom bash scripts,  is to see exactly what kind of API this deployment system supports.

The help messages in the project homepage were really confusing:

```
cap deploy:revert_release          # Revert to previous release timestamp
cap deploy:reverted                # Reverted
cap deploy:reverting               # Revert server(s) to previous release
cap deploy:rollback                # Rollback to previous release
```

Can these steps be clarified a bit in documentation?

**Comment by leehambley** [comment]
Doc improvements probably belong over at capistrano/documentation ?

**Comment by gagarine** [comment]
Yes this it's the capistrano documentation. Please open the bug on their repository.
